### ISSUE TITLE
[Feature] Search-bar near status bar

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#1]
option to move search-bar directly under the status bar sharing the background

**Comment by daffydock** [comment]
Sounds interesting, aesthetically and I think it could look good. However, if you do go ahead, having the end results closer to the bottom, easy to reach via thumb should remain the imperative, in my humble opinion. That is one of the things I like of KISS and your launcher. It's usability without having to use both hands, since the results are easily reachable one handed and without fuzz.

**Comment by TBog** [comment]
* You don't have to reach the search bar with your thumb, the keyboard should open when the search bar is displayed.
* The list will have the option to be reversed.

**Comment by daffydock** [comment]
Fair. And no worries. It is just that sometimes, the data gets moved upward or it was done in such a way due to design cues or keeping up with the google search/browser address bar aesthetic.

Sesame Shortcuts used to have it that way for ages. I just wanted to know your take on it. You are right that if the results are reacheable that it would in fact look pretty cool, depending on how you go about it.

**Comment by daffydock** [comment]
Just curious, are you still working on this feature? 

I must admit that it really did pick my curiosity.

**Comment by TBog** [comment]
I can't give an ETA, but it's something I wanted to do so I'll get to it at some point.

**Comment by daffydock** [comment]
Totally fine. Was not wondering about an ETA. Was just curious as to your thoughts on it.
