### ISSUE TITLE
Tagged shortcuts started showing up in action "Un-tagged"

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#143]
# Description #

I think since a 6.2 development build, all my shortcuts that _are tagged_ started showing up when using the action `Un-tagged`.

## Device info ##

  * OS: Android 10
  * TinyBit Launcher version: 6.2.dev*

**Comment by TBog** [comment]
Tags are stored in two places. 
1. In a HashMap in `TagsHandler`
2. For each Entry that can be tagged

What happened was that the entries loaded before the tags handler finished reading the database.
It's probably a side-effect of migrating away from AsyncTask. Now more stuff can happen at the same time thus faster start-up.
The fix for this was already in place for apps, but because I don't use shortcuts much I forgot about them. :flushed:

**Comment by ltGuillaume** [comment]
Thx for the explanation. Oh the perils of asynchronous processes 💆

**Comment by ltGuillaume** [comment]
Fixed!
