### ISSUE TITLE
[FEATURE] Change base color of entire app

### ISSUE THREAD

**Issue by sundayLOOKplants** [TBog/TBLauncher#176]
Changing the colour scheme from the default green is really hard right now. As-is, you have to set individual colours for each UI element.

It would be nice if you could select one colour and have the app choose matching colours for the UI with simple HSL arithmetics.
Some manual adjustments might be necessary, but this would still be a big step up from clicking each colour setting one by one.

**Comment by TBog** [comment]
1. We could use the backup import functionality to add a couple of default themes, but I don't have the eye for colors.
2. The "auto colors" using HSL arithmetics is possible especially because I already do this for the border of the color previews in the settings activity. But I think only one color is not enough. Maybe two?
