### ISSUE TITLE
Unreliable behaviour of: <"Back" Action when closing keyboard>

### ISSUE THREAD

**Issue by victor0d** [TBog/TBLauncher#235]
The option <"Back" Action when closing keyboard> within <Behaviour> seems to behave differently depending on other options related to what "Back" Action is selected.

I have not completely be able to isolate all the other conditions, but depending on several options set, sometimes it does indeed behaves like expected (not executing the "Back" Action) but in other cases it does execute it.

It is quite easy to reproduce playing a little bit with the "Back" Action options.

Device: Oneplus6
OS: CRDroid6.23(Android10)
TBLauncher: 6.8

**Comment by TBog** [comment]
It would be great if you could provide an example of a desired behavior and an example of a not desired behavior.
I need the settings you are using in both cases so that I can understand what is happening within the code.
I understand it's obvious from your perspective but it may not be from mine.
When I have time to work on the launcher I don't want to spend time testing a feature just to find out I don't understand what you really wanted.
I'll just leave this issue in the backlog even tho' it looks like a quick fix.

**Comment by victor0d** [comment]
Hi TBog, you are completely right.

Rather than a picture, i will upload a quick video (6s) that shows how, when dismissing the keyboard it executes "Back" Action going back to Widgets Screen. Obviously the Option <"Back" Action when closing keyboard> is disabled.

I attach also a copy of the settings I have (xml).

Thanks a lot TBog. It is really getting cool your Launcher.

https://user-images.githubusercontent.com/90806717/150638860-659bb0c2-8c75-47c4-aea7-52ce28416189.mp4

[backup.xml.zip](https://github.com/TBog/TBLauncher/files/7918332/backup.xml.zip)

**Comment by victor0d** [comment]
I will close this issue because it should be linked to [Back key in Search_Desktop is applied twice](https://github.com/TBog/TBLauncher/issues/238) where the information provided is better and the problem more clear.
