### ISSUE TITLE
Termux second widget not showing

### ISSUE THREAD

**Issue by TBog** [TBog/TBLauncher#297]
Q: Did you install [Termux:Widget](https://f-droid.org/en/packages/com.termux.widget/)?
A: Yes I did install it, it has two widgets, the scripts list and the icon script, the latter is the one that is missing (you can see both [here](https://github.com/termux/termux-widget#script-icon-directory-optional) side by side).

So the issue is that the second widget can't be found when I try to add it from the widgets list in TBLauncher but when I change the launcher to the default I can see the two.

_Originally posted by @heiwiper in https://github.com/TBog/TBLauncher/issues/71#issuecomment-1144838123_

**Comment by heiwiper** [comment]
I just realized it was a shortcut widget (just like when you add a website as a shortcut using the browser) which was added to the apps list in TBLauncher.
Thanks for your help, it was apparently not an issue to begin with.

**Comment by heiwiper** [comment]
I think this is actually still an issue, it was my bad for thinking it was resolved.

I was trying to add another termux shortcut today which I totally forgot how I did last time. So the only way to add that shortcut is to switch to the default launcher temporarily aka click "Just now" instead of "Always" when the Android bottom drawer opens, and then hold click the Termux:Widget app to add a widget. After selecting the shortcut widget, the shortcut dialog from TBLauncher should popup since we only switched to the default launcher temporarily. This should make the new shortcut appear in TBLauncher's apps list.

This issue seems to be related to Termux:Widget only, I'm not sure why since I don't have a good Android knowledge. But the workaround that I described should work for every Android device as long as they have the default launcher that has access to that widget which isn't accessible from TBLauncher.
