### ISSUE TITLE
Keep search bar in widget mode

### ISSUE THREAD

**Issue by DonPicciotto** [TBog/TBLauncher#344]
Hi, I'm really sorry if I'm just dumb and didn't find already this option, but I think it would be great to have search bar under dock on widget view too. Do you think it could be possible?
And of course thanks for your work :)

**Comment by TBog** [comment]
This app has 3 screens.
1. Empty screen
2. Search screen
3. Widget screen

The search bar is only visible on the search screen because that's the only screen that was designed to show the result list.

I don't see why you would want to have the **search bar** / **result list** over the widgets.

You can set a gesture to open the keyboard and show the search screen

**Comment by DonPicciotto** [comment]
Hi, and thanks for the answer :). The widget page is the main page I use and I think it could be useful to launch search with only one tap, without waiting for the animation when using a gesture and actually "freeing" a gesture slot. If I remember correctly, this should be possible in the original kiss launcher.
Again, thanks for your time and sorry for my late reply
17 set 2022, 17:26 da ***@***.***:

**Comment by TBog** [comment]
Set tap empty screen gesture to show search with keyboard.

I don't think showing widgets under the result list is ok.
I also have a problem with opening the keyboard while the widgets are on the screen.
