### ISSUE TITLE
Shortcuts created from Browsers output error.

### ISSUE THREAD

**Issue by daffydock** [TBog/TBLauncher#62]
**Describe the bug**
Unaware launcher version started this. Since I literally switched to TinyBit launcher due to this functionality working over KISS, where it also does not work.

**To Reproduce**
1. Go to any browser
2. Make shortcut of any website, as to appear on Launcher
3. Select shortcut. Error reads: "Whooops... Unable to launch that app."
4. Not profit. 

**Expected behavior**
Shortcut should launch website once found and activated. Regular searches do work. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: LG Stylo 3 Plus
 - OS: Android 
 - Version: 7.0 

**Additional context**
I also have a 7.1.2 device and it does not work there. I also have a 10 device and it works.

**Comment by TBog** [comment]
Since Android Oreo (ver 8.0) the way shortcuts are handled has changrd. This has caused KISS to store both a shortcut ID and a serialized intent. Also KISS lets you regenerate dynamic shortcuts.

Some of this has been inherited into TBL. I couldn't test it on a Nougat phone. I'll see what I can do to test or at least go through the code again to try and spot any problems.

**Comment by TBog** [comment]
fixed with commit bf81c1bbd059d2f31d8a0a23ec276ddb87cd09cf

**Comment by TBog** [comment]
you can test it in release [v4.7-dev.2](https://github.com/TBog/TBLauncher/releases/tag/v4.7-dev.2)

**Comment by daffydock** [comment]
Tested. Functionality is back. I appreciate the fix and explanation. Thanks!
