### ISSUE TITLE
[FEATURE] Add (icon-only) app/activity shortcuts to the widget view

### ISSUE THREAD

**Issue by ltGuillaume** [TBog/TBLauncher#71]
**Describe the solution you'd like**
This might be considered as going against the philosophy of KISS/TBLauncher, but I do think there would be great benefits to allowing the user to add shortcuts to apps and specific app activities to the widget view. This would reduce the user's actions to reach the activities by at least 2 taps and it would most definitely make TBLauncher a lot more accessible to the bigger audience that is used to more traditional launchers.

**Comment by TBog** [comment]
Right now I use [Bubble Cloud](https://play.google.com/store/apps/details?id=dyna.logix.bookmarkbubbles.widgets) in order to have Apps on the widget page.

I'll make my own widget with similar functionality after I feel I have a good and stable launcher with a tutorial, FAQ or wiki page.

**Comment by ltGuillaume** [comment]
That's great to hear and thanks for the suggestion!

**Comment by heiwiper** [comment]
Is this still not implemented ? I'm trying to add termux icon widget but I can't find it in the widgets list.

**Comment by TBog** [comment]
> Is this still not implemented ? I'm trying to add termux icon widget but I can't find it in the widgets list.

Did you install [Termux:Widget](https://f-droid.org/en/packages/com.termux.widget/)?

**Comment by heiwiper** [comment]
Yes I did install it, it has two widgets, the scripts list and the icon script, the latter is the one that is missing (you can see both [here](https://github.com/termux/termux-widget#script-icon-directory-optional) side by side).
So the issue is that the second widget can't be found when I try to add it from the widgets list in TBLauncher but when I change the launcher to the default I can see the two.
